plethora of fixes

diff --git a/local/bin/nn b/local/bin/nn
--- a/local/bin/nn
+++ b/local/bin/nn
@@ -1,5 +1,9 @@
 #!/bin/sh
-inbox=${1:-$NOTES_FILE} def=Chores addc='<Add category>' deln='<Delete>'
+inbox=${1:-$NOTES_FILE} t=/tmp/$$ def=Chores addc='<Add category>' deln='<Delete>'
+trap 'rm -f $t' 0 1 2 3 15
+case $inbox in [!/]*) inbox=`pwd`/$inbox; esac
+test ! -f "$inbox" && log 'Missing file\n' 31 && exit
+test ! -d ${NOTES_DIR?} && mkdir -p $NOTES_DIR
 
 log() { printf "\033[2K\r\033[1;${2:-33}m${1}\033[0m"; }
 add() { printf '%s\n' "$*" >>$c && del; }
@@ -8,9 +12,6 @@ del() { ed - $inbox <<-\#
 	w
 	#
 }
-case $inbox in [!/]*) inbox=`pwd`/$inbox; esac
-test ! -f "$inbox"      && log 'Missing file\n' 31 && exit
-test ! -d ${NOTES_DIR?} && mkdir -p $NOTES_DIR
 
 chdir $NOTES_DIR
 >>$def
@@ -21,15 +22,14 @@ while test -s $inbox; do
 	c=`printf '%s\n' * "$addc" "$deln" | fzf`
 	case $c in
 	"$addc")	log 'Enter title:\n' 36; read c; test "X$c" = X && continue
-			test ! -f "$c" && add "$note" ||
+			test ! -f $c && add "($c)" "$note" ||
 				{ tput clear; log 'Duplicate\n' 31; sleep 1;} ;;
 	"$deln")	log 'Delete?' 31; a=`printf '%s\n' yes no | fzf`
 			test "$a" = yes && del;;
 	'')		tput clear; log 'Interrupted\n' 31; exit;;
-	*)		add "$note"
+	*)		add "($c)" "$note"
 	esac
 done
-
 tput clear
-for i in *; do test -s $i && mail -s $i $USER <$i &&  >$i; done
+cat * >$t; test -s $t && <$t mail $USER && for i in *; do  >$i; done
 log 'All done!\n' 34
